// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SanPhamDBContext))]
    [Migration("20251026153252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.SanPham", b =>
                {
                    b.Property<int>("idSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idSP"));

                    b.Property<decimal>("giaSP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("loaiSP")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("motaSP")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("tenSP")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tinhtrangSP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("idSP");

                    b.ToTable("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
